# Generated by Django 4.0.5 on 2022-06-20 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_user_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='admin_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
