# Generated by Django 4.0.5 on 2023-06-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_community_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
