name: Build & Publish Image

on:   
  workflow_run:
    workflows: ["Quality Checks"]
    branches: [main]
    types: [completed]

env:
  BACKEND_IMAGE_NAME: map_kit_backend

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}

      - name: Build image
        run: docker build . --tag $BACKEND_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Publish image
        run: |
          IMAGE_ID=registry.digitalocean.com/map-kit-backend/$BACKEND_IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $BACKEND_IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
